
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-12
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-index-create-instructors","number":47,"title":"yz-Create frontend Index and Create pages for instructors","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/47"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-RosterStudents-page","number":46,"title":"aw - Index page for Roster Students","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/46"},{"author":{"id":"U_kgDOB3b6TA","is_bot":false,"login":"Hungkhuu04","name":""},"headRefName":"hk-frontiers-startup","number":44,"title":"hk - FEATURE - ADMIN_EMAILS are added to the admins table at startup. #6","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/44"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"simon-studentcoursestaff","number":43,"title":"simony05 - added controller for students to see courses where they  are staff in","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/43"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"simon-coursestaff","number":42,"title":"simony05 - Added table for CourseStaff with Post and Get methods","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/42"},{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-RosterStudents-form","number":41,"title":"aw - RosterStudentsForm","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/41"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-create-RoleEmailTable","number":40,"title":"jj - Create RoleEmailTable for Admin and Instructors","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/40"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-create-RoleEmailForm","number":35,"title":"jj - created RoleEmailForm for Admin and Instructors","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/35"}]
