
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-12
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-rosterstudents-delete-endpoint","number":30,"title":"jj - BACKEND - Add delete for roster student","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/30"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-instructor-controller","number":29,"title":"yz-Create Backend CRUD operations for Instructor table (Admin only) (no Update actually; only CRD).","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/29"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-instructor-table","number":28,"title":"Create Instructor Table (entity and repository)","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/28"}]
