
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-12
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-12
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwOTM2NDI2","is_bot":false,"login":"arthurwu17","name":"Arthur Wu"},"headRefName":"aw-RosterStudents-page","number":46,"title":"aw - Index page for Roster Students","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/46"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"simon-studentcoursestaff","number":43,"title":"simony05 - added controller for students to see courses where they  are staff in","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/43"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"simon-coursestaff","number":42,"title":"simony05 - Added table for CourseStaff with Post and Get methods","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/42"}]
