
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-12
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-12
pull_requests: [{"author":{"id":"U_kgDOB3b6TA","is_bot":false,"login":"Hungkhuu04","name":""},"headRefName":"hk-crud-admintable","number":39,"title":"hk - Create Backend CRUD operations for Admin Table (Admin only), (no Update actually; only CRD).","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/39"},{"author":{"id":"U_kgDOB3b6TA","is_bot":false,"login":"Hungkhuu04","name":""},"headRefName":"hk-AdminTable","number":37,"title":"hk - CREATE Admin Table","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/37"},{"author":{"id":"MDQ6VXNlcjY3NTU5NDUy","is_bot":false,"login":"simony05","name":"Simon Yan"},"headRefName":"simon-studentcourses","number":36,"title":"Added controller for students to see courses they are enrolled in","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/36"},{"author":{"id":"MDQ6VXNlcjc4NzczNjU1","is_bot":false,"login":"tizerk","name":"Jay Joo"},"headRefName":"jj-create-RoleEmailForm","number":35,"title":"jj - created RoleEmailForm for Admin and Instructors","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/35"},{"author":{"id":"U_kgDOB7QARg","is_bot":false,"login":"mic-wu","name":""},"headRefName":"mw-rosterstudents-table-component","number":33,"title":"mw - Add table component for RosterStudents plus stories and tests","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/33"},{"author":{"id":"MDQ6VXNlcjQwNDQzMzY4","is_bot":false,"login":"yxz29315","name":"Shawn Zhang"},"headRefName":"yz-instructor-controller","number":29,"title":"yz-Create Backend CRUD operations for Instructor table (Admin only) (no Update actually; only CRD).","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-12/pull/29"}]
